'use client';

import { TestPlan, TestScenario } from '@/lib/types/assurance';
import { useState } from 'react';
import { CheckCircle2, XCircle, Filter, Sparkles } from 'lucide-react';

interface TestPlanViewerProps {
  testPlan?: TestPlan | {
    total_candidates_generated?: number;
    total_scenarios_selected?: number;
    candidate_count?: number;
    selected_count?: number;
    reduction_pct?: number;
    selected_scenarios?: TestScenario[];
    scenarios?: TestScenario[];
  } | null;
  onSelectScenario?: (scenario: TestScenario) => void;
  selectedScenarioId?: string;
  isCompleted?: boolean;
}

export function TestPlanViewer({
  testPlan,
  onSelectScenario,
  selectedScenarioId,
  isCompleted = true,
}: TestPlanViewerProps) {
  const [categoryFilter, setCategoryFilter] = useState<string>('ALL');

  const rawScenarios =
    (testPlan as any)?.selected_scenarios ||
    (testPlan as any)?.scenarios ||
    [];

  const candidateCount =
    (testPlan as any)?.total_candidates_generated ||
    (testPlan as any)?.candidate_count ||
    rawScenarios.length;

  const selectedCount =
    (testPlan as any)?.total_scenarios_selected ||
    (testPlan as any)?.selected_count ||
    rawScenarios.length;

  const reductionPct =
    (testPlan as any)?.reduction_pct ||
    (candidateCount > 0 ? Math.round(((candidateCount - selectedCount) / candidateCount) * 100) : 0);

  if (!rawScenarios || rawScenarios.length === 0) {
    return (
      <div className="rounded-xl border border-slate-800 bg-slate-900/50 p-8 text-center text-slate-400">
        {isCompleted
          ? 'No test failures reproduced. All pricing test cases matched 100%.'
          : 'Test scenarios are being generated by TestPlannerAgent...'}
      </div>
    );
  }

  const categories: string[] = Array.from(
    new Set(rawScenarios.map((s: any) => String(s.category || 'General')))
  );

  const filteredScenarios =
    categoryFilter === 'ALL'
      ? rawScenarios
      : rawScenarios.filter((s: TestScenario) => (s.category || 'General') === categoryFilter);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="text-base font-semibold text-white flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-sky-400" />
            Risk-Directed Test Plan ({rawScenarios.length} Scenarios)
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Optimized from {candidateCount} candidate scenarios ({reductionPct}% reduction via AST boundary analysis)
          </p>
        </div>

        {/* Category filter */}
        <div className="flex items-center gap-2">
          <Filter className="h-4 w-4 text-slate-400" />
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-1.5 text-xs text-slate-200 focus:border-sky-500 focus:outline-none"
          >
            <option value="ALL">All Categories ({rawScenarios.length})</option>
            {categories.map((cat) => (
              <option key={cat} value={cat}>
                {cat}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/80 shadow-xl">
        <table className="w-full text-left text-xs font-sans">
          <thead className="border-b border-slate-800 bg-slate-950 text-slate-400">
            <tr>
              <th className="px-4 py-3 font-medium">Status</th>
              <th className="px-4 py-3 font-medium">Scenario / Category</th>
              <th className="px-4 py-3 font-medium">Key Risk Inputs</th>
              <th className="px-4 py-3 font-medium text-right">Intent Expected</th>
              <th className="px-4 py-3 font-medium text-right">Target Actual</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60 font-mono">
            {filteredScenarios.map((sc: TestScenario) => {
              const isSelected = sc.scenario_id === selectedScenarioId;
              const matches = sc.matches;
              const inputsStr = sc.risk_inputs
                ? Object.entries(sc.risk_inputs)
                    .slice(0, 3)
                    .map(([k, v]) => `${k}=${v}`)
                    .join(', ')
                : '';

              return (
                <tr
                  key={sc.scenario_id}
                  onClick={() => onSelectScenario && onSelectScenario(sc)}
                  className={`cursor-pointer transition-colors hover:bg-slate-800/50 ${
                    isSelected ? 'bg-sky-950/60 font-semibold' : ''
                  }`}
                >
                  <td className="px-4 py-3">
                    {matches ? (
                      <span className="inline-flex items-center gap-1 text-emerald-400 font-bold">
                        <CheckCircle2 className="h-4 w-4" /> MATCH
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 text-rose-400 font-bold">
                        <XCircle className="h-4 w-4" /> MISMATCH
                      </span>
                    )}
                  </td>
                  <td className="px-4 py-3 font-sans">
                    <div className="font-bold text-slate-100">{sc.name || sc.scenario_id}</div>
                    <div className="text-[11px] text-sky-400 font-mono">{sc.category || 'Standard'}</div>
                  </td>
                  <td className="px-4 py-3 text-slate-300 text-[11px]">
                    {inputsStr || 'Default Rating Factors'}
                  </td>
                  <td className="px-4 py-3 text-right text-emerald-400 font-bold">
                    ${typeof sc.expected_premium === 'number' ? (sc.expected_premium as number).toFixed(2) : sc.expected_premium || '0.00'}
                  </td>
                  <td className="px-4 py-3 text-right text-rose-400 font-bold">
                    ${typeof sc.actual_premium === 'number' ? (sc.actual_premium as number).toFixed(2) : sc.actual_premium || '0.00'}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
